### ISSUE TITLE
Directly run the code error

### ISSUE THREAD

**Issue by jsoncool** [zhangzhao156/Human-Activity-Recognition-Codes-Datasets#4]
Hi,when i directly run your code,it reports an error. I think this is may be tensorflow version and keras version is not the same with you.so,what is your tensorflow and keras version ?
![image](https://user-images.githubusercontent.com/24389697/147440680-16701cb5-ae0a-41ec-bb1d-df01c213c2a7.png)

**Comment by zhangzhao156** [comment]
Hi, the tensorflow version maybe <=1.7.0, since most of the experiments were done in 2018.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangzhao156/Human-Activity-Recognition-Codes-Datasets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午2:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4)





 
Hi,when i directly run your code,it reports an error. I think this is may be tensorflow version and keras version is not the same with you.so,what is your tensorflow and keras version ?
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jsoncool** [comment]
> Hi, the tensorflow version maybe <=1.7.0, since most of the experiments were done in 2018.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhangzhao156/Human-Activity-Recognition-Codes-Datasets" ***@***.***&gt;; 发送时间:&nbsp;2021年12月27日(星期一) 下午2:18 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4) Hi,when i directly run your code,it reports an error. I think this is may be tensorflow version and keras version is not the same with you.so,what is your tensorflow and keras version ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

what about keras version?

**Comment by zhangzhao156** [comment]
Hi, the keras version maybe 2.1.5 or 2.1.6, because we have already updated the tensorflow and I didn't remember their exact versions.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangzhao156/Human-Activity-Recognition-Codes-Datasets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4)





  
Hi, the tensorflow version maybe <=1.7.0, since most of the experiments were done in 2018.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhangzhao156/Human-Activity-Recognition-Codes-Datasets" @.&gt;; 发送时间:&nbsp;2021年12月27日(星期一) 下午2:18 @.&gt;; @.&gt;; 主题:&nbsp;[zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4) Hi,when i directly run your code,it reports an error. I think this is may be tensorflow version and keras version is not the same with you.so,what is your tensorflow and keras version ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
what about keras version?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jsoncool** [comment]
> Hi, the keras version maybe 2.1.5 or 2.1.6, because we have already updated the tensorflow and I didn't remember their exact versions.&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhangzhao156/Human-Activity-Recognition-Codes-Datasets" ***@***.***&gt;; 发送时间:&nbsp;2021年12月27日(星期一) 下午3:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4) Hi, the tensorflow version maybe <=1.7.0, since most of the experiments were done in 2018. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhangzhao156/Human-Activity-Recognition-Codes-Datasets" @.&gt;; 发送时间:&nbsp;2021年12月27日(星期一) 下午2:18 @.&gt;; @.&gt;; 主题:&nbsp;[zhangzhao156/Human-Activity-Recognition-Codes-Datasets] Directly run the code error (Issue #4) Hi,when i directly run your code,it reports an error. I think this is may be tensorflow version and keras version is not the same with you.so,what is your tensorflow and keras version ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; what about keras version? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

okey, thanks. it works now
